---
exclude_paths:
- "client/src/main/java/io/spine/net/Patterns.java"
- "core/src/test/**/*.*"
- "client/src/test/**/*.*"
- "server/src/test/**/*.*"
- "testutil-core/src/test/**/*.*"
- "testutil-client/src/test/**/*.*"
- "testutil-server/src/test/**/*.*"
