---
exclude_paths:
- "client/src/main/java/io/spine/net/Patterns.java"
- "base/src/test/**/*.*"
- "client/src/test/**/*.*"
- "server/src/test/**/*.*"
- "server-deployment/src/test/**/*.*"
- "testutil/src/test/**/*.*"
- "time/src/test/**/*.*"
- "values/src/test/**/*.*"
