language: java

env:
  global:
    # Encrypted `CODACY_PROJECT_TOKEN` variable according to:
    # https://docs.travis-ci.com/user/environment-variables/#Encrypting-environment-variables
    - secure: RVrbSK76Ui1JcnfAq8mV11FDkntu/BaJwOiMWIezAEZAenrwtVlnGaP2hZPRvvFV0c/jRnEv6Q1YuhB9rQ0Ldac2TWpTMomfTLzChZmhuev5Ee7bL4cCJ/gROA0cnYrixYLxpLk3yYMiZuJviDuvACzUXkll37lBIOjpXzoKB5xPN1xuw+vtMQ7L+BQLvBJkWgEDGrUMpOXNIph1fBVcANX28AAmlzZuruNdh6jyi97CfIzE5gn1HnKInn8mW1iG5C5kU6uxShVNTav1Moo9mYJTJt0WfTiDPhb6+11uDNtGjmATd73wjccpLKX7QJAqkH2i/jxPFlqB5pgmklmxCgaL/+NqRsN5Ow84bZ8uMH1j8LhdA3o79rYjeCyQ3BOnloGo2t5StXs/v/IZU1KCgCYvh4H26Bw768VsChtWtFVo+FxFoKub/AaVUmUtBTB63VKgr0iFIJSpSzMpXMFuvVBJ2y54UsOvZw1XL9IM+SYkgVBDd1fAwPT3nfNDUYfDbECzd7FbLhg0vvzhagOZCz/jbN8FEyauPFXQ4xwLoI6kKLoQSkF8qOr+dLbyXEKHSXxAt8lnIeGAJrSEmPiOv69JBirjSR0OMfaT/KL+cfQ2AJ6Hhc5XNmFQjIELP42Jmd+tmTBD2nfwY76vrU132C/nzoAGXkUME2hGbnvlrRg=

before_install:
  - chmod +x gradlew
  # Codacy setup. See: https://github.com/codacy/codacy-coverage-reporter#build-from-source.
  # Manually downloading the latest version from the Maven Central, since the jpm4j stopped working.
  - curl -sL  http://repo1.maven.org/maven2/com/codacy/codacy-coverage-reporter/1.0.13/codacy-coverage-reporter-1.0.13-assembly.jar >> codacy-coverage-reporter.jar
  # END of Codacy setup.

after_success:
  # See: https://github.com/codecov/example-java/blob/master/.travis.yml
  - bash <(curl -s https://codecov.io/bash)
  # Codacy setup. https://github.com/codacy/codacy-coverage-reporter#build-from-source
  - java -cp ./codacy-coverage-reporter.jar com.codacy.CodacyCoverageReporter -l Java -r ./build/reports/jacoco/jacocoRootReport/jacocoRootReport.xml
  # END of Codacy setup.
  - chmod +x ./scripts/publish-artifacts.sh
  - ./scripts/publish-artifacts.sh

script: ./gradlew check --stacktrace

before_deploy:
  - mkdir archives
  - zip -r archives/reports.zip **/build/reports

deploy:
  provider: gcs
  access_key_id: GOOGX66ER6DXLZH7IKQF
  secret_access_key:
      secure: f1I4fDf+X/RM998YVCRsOzh1PkaVyaW7Z5Sqr89M30VTT3FV8V+dcpIpqWbe1jRXfPc5egUk/161PqxNKZcjMftRcjox1IVwC+xEfadDZGKDTRkIlmKINe8xHDnYUYmQZzR7AVKjk5JsnDD7qZjONEjGqM2ZilZ0Ht4er+DAfydqGOU75FkVMKX75vGFfcsXHqVFbGWjlRjRGTBswrkImH6CSmWol3YOG8S/Ar34dBPBbVQwZiI9dggF8irbO1kSUGz2Hz3KV48vZ/6D/8/eAcS1WAnU0bW4gMdKHf27LX70HqAUE94IQNZXuIgt4bK697cxz6F+ngC+0DClHaxopbrobRkU79kV/IQf+HKqdwxkGTfe9bTWoWp9KZ9qlztQDBR+brkohmnaBc9BVKcYJG1DMsBz8FRWkVzjaxe61G5RMdTER+wscAxEieqWfFj9xOQWcqqf7YWo8Ri42GJHGGjHat3OuzbeDuM3LV/5CthlC9BNEHmxHF/kTpyU+M/KPVvb+Y9JCqKjlGbPC35Nx/ms46bth8M3i/ynNWM8GMLBzPUZp74V2F4qFgk4AIiASJ2ix/Hs1PMt5rZxcZmk9L0SmkaHufLpH7hhDY0CZwnCqrFq00MmqCuo9L9aojAsgQb111e+szCXjSWV81jeK27gMPsLZZaXiRlPCam9S0c=
  bucket: spine-dev.appspot.com
  upload-dir: core-java/builds/${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}-${TRAVIS_BUILD_NUMBER}
  local-dir: archives
  skip_cleanup: true
  on:
    repo: SpineEventEngine/core-java
    all_branches: true
