language: java

env:
  global:
    # Encrypted `CODACY_PROJECT_TOKEN` variable according to:
    # https://docs.travis-ci.com/user/environment-variables/#Encrypting-environment-variables
    - secure: RVrbSK76Ui1JcnfAq8mV11FDkntu/BaJwOiMWIezAEZAenrwtVlnGaP2hZPRvvFV0c/jRnEv6Q1YuhB9rQ0Ldac2TWpTMomfTLzChZmhuev5Ee7bL4cCJ/gROA0cnYrixYLxpLk3yYMiZuJviDuvACzUXkll37lBIOjpXzoKB5xPN1xuw+vtMQ7L+BQLvBJkWgEDGrUMpOXNIph1fBVcANX28AAmlzZuruNdh6jyi97CfIzE5gn1HnKInn8mW1iG5C5kU6uxShVNTav1Moo9mYJTJt0WfTiDPhb6+11uDNtGjmATd73wjccpLKX7QJAqkH2i/jxPFlqB5pgmklmxCgaL/+NqRsN5Ow84bZ8uMH1j8LhdA3o79rYjeCyQ3BOnloGo2t5StXs/v/IZU1KCgCYvh4H26Bw768VsChtWtFVo+FxFoKub/AaVUmUtBTB63VKgr0iFIJSpSzMpXMFuvVBJ2y54UsOvZw1XL9IM+SYkgVBDd1fAwPT3nfNDUYfDbECzd7FbLhg0vvzhagOZCz/jbN8FEyauPFXQ4xwLoI6kKLoQSkF8qOr+dLbyXEKHSXxAt8lnIeGAJrSEmPiOv69JBirjSR0OMfaT/KL+cfQ2AJ6Hhc5XNmFQjIELP42Jmd+tmTBD2nfwY76vrU132C/nzoAGXkUME2hGbnvlrRg=

before_install:
  - chmod +x gradlew
  # Codacy setup. See: https://github.com/codacy/codacy-coverage-reporter#build-from-source.
  # Manually downloading the latest version from the Maven Central, since the jpm4j stopped working.
  - curl -sL  http://repo1.maven.org/maven2/com/codacy/codacy-coverage-reporter/1.0.13/codacy-coverage-reporter-1.0.13-assembly.jar >> codacy-coverage-reporter.jar
  # END of Codacy setup.

deploy:
  provider: gcs
  access_key_id: GCS_KEY
  secret_access_key:
      secure: "L9I+KVv5yYZ2f8vKhmT6a76hMoHY8HoYXngx+v/Uf6Szg59usSaONe9Wcl5CBQ9HGazG2vv1lBRVBylFZvqmZl5HFq1RfoqXVejLU92VHDlYcHLG6d81F1ycZ4DU+0ZtqMxZQxmBHDsUhtUuj+993fqHdtty/A2bdxYlpp83yM/35/BWVpT+fQjkjPtQEoq0IycOTfVVqPyYrbLlt8lkKP68x63VspaDKGKK0WFSbforXAXUaGBtrDXNbM7BSxsi1rEYKHuUKGfwzenCLFbIco3XWyFd1TF4R0Rfgw7INL6tSZ+GnFq18cUtklNh1OwQhQzcjiMk6G4IEWoHjRL3w3yNGUV2rz8MCFqbnu/ZB9U5i3HUwAvouV/qLSocJmzPk3SOvCYsbODy69LuOh29GWk0tfvxXKWd5sctOVpKI8o8/nxCfEBTStAd1bGqLT093hkR9N8eg1/QiOIvpUAw3o+L7CPM+1uJfCQWbt6niSP776UvKS7O8+NbVuK+yorayD/PvnyZ6h/+q78y6A7nY/Ky4PRZ5I1X5wTIEe3UHIBNUWxDk1jm77RkvYPyxk6XoW8EmtyGSw8+EjJfyKZNrJv1W13B71ZGpN1Kj08vJqkgObPMyKixLtRpTsYDh38zeU4Acy35+sAClVBuLRItAVTXdASayj81CQ39n6nRcPw="
  bucket: spine-dev.appspot.com
  skip_cleanup: true
  on:
    repo: SpineEventEngine/core-java
    all_branches: true

after_success:
  # See: https://github.com/codecov/example-java/blob/master/.travis.yml
  - bash <(curl -s https://codecov.io/bash)
  # Codacy setup. https://github.com/codacy/codacy-coverage-reporter#build-from-source
  - java -cp ./codacy-coverage-reporter.jar com.codacy.CodacyCoverageReporter -l Java -r ./build/reports/jacoco/jacocoRootReport/jacocoRootReport.xml
  # END of Codacy setup.
  - chmod +x ./scripts/publish-artifacts.sh
  - ./scripts/publish-artifacts.sh

script: ./gradlew check --stacktrace
